# Generated by Django 5.0.7 on 2024-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='documentos_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='fotos_produtos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_produtos/'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='preco_comprado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
