# Generated by Django 5.0.7 on 2024-07-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_alter_estoque_altura_alter_estoque_comprimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='material_usado',
        ),
        migrations.AlterField(
            model_name='pedidomaterial',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_material', to='gerenciamento.pedido'),
        ),
    ]
