# Generated by Django 5.0.7 on 2024-07-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_remove_pedido_material_usado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomaterial',
            name='quantidade_utilizada',
            field=models.IntegerField(),
        ),
    ]
