# Generated by Django 5.0.7 on 2024-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('tecnico', 'Tecnico'), ('marceneiro', 'Marceneiro'), ('administrativo', 'Administrativo'), ('carpinteiro', 'Carpinteiro'), ('eletricista', 'Eletricista'), ('motorista', 'Motorista')], default='', max_length=20),
        ),
    ]
