# Generated by Django 5.0.7 on 2024-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0007_pedido_funcionario_pedidomaterial_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documentos_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos_cliente/'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='documentos_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos_fornecedor/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='documentos_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos_funcionarios/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fotos_funcionarios',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='documentos_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos_produto/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fotos_produto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_produto/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('producao', 'Produção'), ('administracao', 'Administração'), ('almoxarifado', 'Almoxarifado'), ('compras', 'Compras'), ('comercial', 'Comercial')], default='', max_length=255),
        ),
    ]
